### ISSUE TITLE
cannot read property 'currentlyUsingBlocks' of null

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#60]
```
droplet.js:620 Uncaught TypeError: Cannot read property 'currentlyUsingBlocks' of null
  at attachToAce (http://localhost:5050/static/plugins/c9.ide.cs50.droplet/droplet.js:620:65)
  at exports.EventEmitter.<anonymous> (http://localhost:5050/static/plugins/c9.ide.ace/ace.js:1910:21)
  at exports.EventEmitter.EventEmitter.emit (http://localhost:5050/static/lib/events.js:89:33)
  at exports.EventEmitter.EventEmitter.addListener (http://localhost:5050/static/lib/events.js:165:14)
  at Plugin.on (http://localhost:5050/static/plugins/c9.core/ext.js:853:27)
  at exports.EventEmitter.<anonymous> (http://localhost:5050/static/plugins/c9.ide.cs50.droplet/droplet.js:189:42)
  at exports.EventEmitter.EventEmitter.emit (http://localhost:5050/static/lib/events.js:89:33)
  at Function.sticky (http://localhost:5050/static/plugins/c9.core/ext.js:344:28)
```

![currently-using-blocks-of-null](https://user-images.githubusercontent.com/7230211/28725406-54bd2f22-738b-11e7-9d1d-00a6b6b0ded9.gif)

**Comment by dabbler0** [comment]
Bundled into commit c8258ba49ab19e8b46796eed534e04a732e16e82.
