### ISSUE TITLE
cannot read property 'cursor' of null

### ISSUE THREAD

**Issue by kzidane** [cs50/harvard.cs50.droplet#62]
```
droplet-full.js:30 Uncaught TypeError: Cannot read property 'cursor' of null
  at a.s.getCursor (http://localhost:5050/static/plugins/c9.ide.cs50.droplet/lib/droplet/droplet-full.js:30:24177)
  at a.s.cursorAtSocket (http://localhost:5050/static/plugins/c9.ide.cs50.droplet/lib/droplet/droplet-full.js:30:8706)
  at a.<anonymous> (http://localhost:5050/static/plugins/c9.ide.cs50.droplet/lib/droplet/droplet-full.js:32:5289)
  at HTMLDivElement.<anonymous> (http://localhost:5050/static/plugins/c9.ide.cs50.droplet/lib/droplet/droplet-full.js:28:18178)
```

If I save the file and I hit Ctrl after I get this error:
![cursor](https://user-images.githubusercontent.com/7230211/28795181-e9c0ecee-7606-11e7-9439-ec7475f56727.gif)

**Comment by dabbler0** [comment]
This was a bug where Droplet keypress handlers were still around even when Droplet wasn't active. This is fixed now for this and all the other similar DOM handlers.
